version: '3.8'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: Yash
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: grocery_booking
    ports:
      - "5432:5432"
    volumes:
      - ./src/sql/init.sql:/docker-entrypoint-initdb.d/init.sql 

  grocery-booking-app:
    build: 
      context: . 
    ports:
      - "3000:3000"  
    depends_on:
      - postgres  
